const { PDFDocument, StandardFonts, rgb, degrees } = PDFLib;
pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js";
const $ = (s) => document.querySelector(s);
const state = { files: [], redaction: { file: null, doc: null, pageNumber: 1, pageCount: 0, scale: 1.5, mode: "rect", rects: {}, drawing: null, renderToken: 0 } };
const tool = $("#tool"), fileInput = $("#fileInput"), fileList = $("#fileList"), activeTool = $("#activeTool"), notice = $("#toolNotice"), acceptText = $("#acceptText");
const rangeWrap = $("#rangeWrap"), watermarkWrap = $("#watermarkWrap"), angleWrap = $("#angleWrap"), rangeInput = $("#rangeInput"), watermarkInput = $("#watermarkInput"), angleInput = $("#angleInput");
const results = $("#results"), progress = $("#progress"), progressText = $("#progressText"), progressNumber = $("#progressNumber"), progressBar = $("#progressBar");
const redactStudio = $("#redactStudio"), emptyState = $("#emptyState"), canvasShell = $("#canvasShell"), canvasStack = $("#canvasStack"), pdfCanvas = $("#pdfCanvas"), overlayCanvas = $("#overlayCanvas");
const pdfCtx = pdfCanvas.getContext("2d", { alpha: false }), overlayCtx = overlayCanvas.getContext("2d");
const pageLabel = $("#pageLabel"), rectCount = $("#rectCount"), viewerTitle = $("#viewerTitle"), zoomInput = $("#zoomInput"), rectTool = $("#rectTool"), panTool = $("#panTool");
const toolInfo = {
  merge: ["PDF 合并", "将多个 PDF 合并为一个新 PDF。", ".pdf", "pdf"],
  split: ["PDF 拆分", "按页码范围生成一个或多个 PDF。多个范围用分号分隔。", ".pdf", "pdf"],
  delete: ["删除指定页面", "输入要删除的页码，例如 2,4-6。", ".pdf", "pdf"],
  extract: ["页面提取 / 重排", "按输入顺序生成新 PDF，例如 3,1,2。", ".pdf", "pdf"],
  rotate: ["PDF 页面旋转", "按页码范围旋转页面，留空表示全部页面。", ".pdf", "pdf"],
  watermark: ["PDF 加水印", "在每页写入文字水印并导出。", ".pdf", "pdf"],
  images: ["图片转 PDF", "将 JPG、PNG、WebP 按顺序生成 PDF。", ".png,.jpg,.jpeg,.webp", "image"],
  pdfimages: ["PDF 转图片 ZIP", "将 PDF 每页渲染为 PNG 并打包下载。", ".pdf", "pdf"],
  compress: ["PDF 压缩（有限）", "重写 PDF 对象流，无法保证图片型 PDF 明显变小。", ".pdf", "pdf"],
  redact: ["PDF 可视化涂黑", "在页面上画框，导出时永久涂黑并栅格化。", ".pdf", "pdf"],
  pdf2word: ["PDF 转 Word（需转换引擎）", "高保真 PDF 转 Word 需要专门转换引擎，当前不伪装已完成。", ".pdf", "pdf"],
  office2pdf: ["Word/PPT 转 PDF（需转换引擎）", "Office 转 PDF 需要 LibreOffice、桌面引擎或服务端转换。", ".doc,.docx,.ppt,.pptx", "office"]
};
function formatBytes(bytes){ if(bytes<1024)return `${bytes} B`; if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`; return `${(bytes/1048576).toFixed(1)} MB`; }
function setProgress(value,text){ progress.classList.add("active"); progressBar.style.width=`${value}%`; progressNumber.textContent=`${value}%`; progressText.textContent=text; }
function addResult(name, bytes, type="application/pdf"){ const blob=new Blob([bytes],{type}); const url=URL.createObjectURL(blob); const item=document.createElement("div"); item.className="resultItem"; item.innerHTML=`<div><strong>${name}</strong><small>${formatBytes(blob.size)}</small></div>`; const a=document.createElement("a"); a.className="download"; a.href=url; a.download=name; a.textContent="下载"; item.append(a); results.append(item); }
function renderFiles(){ fileList.innerHTML=state.files.length ? state.files.map((f,i)=>`<div class="fileItem"><div><strong>${f.name}</strong><small>${formatBytes(f.size)}</small></div><button class="secondary" data-remove="${i}" type="button">移除</button></div>`).join("") : '<p class="hint">还没有选择文件。</p>'; }
function parseRanges(input,pageCount){ const text=(input||`1-${pageCount}`).replace(/\s/g,""); const pages=[]; text.split(",").filter(Boolean).forEach(part=>{ if(part.includes("-")){ const [s,e]=part.split("-").map(Number); if(!s||!e||s>e) throw new Error(`页码范围不合法：${part}`); for(let i=s;i<=e;i++) pages.push(i-1); } else { const p=Number(part); if(!p) throw new Error(`页码不合法：${part}`); pages.push(p-1); } }); pages.forEach(p=>{ if(p<0||p>=pageCount) throw new Error(`页码超出范围：${p+1}`); }); return pages; }
async function readPdf(file){ return PDFDocument.load(await file.arrayBuffer(), { ignoreEncryption:true }); }
async function mergePdfs(){ if(state.files.length<2) throw new Error("PDF 合并至少需要 2 个 PDF。"); const out=await PDFDocument.create(); for(const f of state.files){ const src=await readPdf(f); const pages=await out.copyPages(src,src.getPageIndices()); pages.forEach(p=>out.addPage(p)); } addResult("merged.pdf", await out.save({useObjectStreams:true})); }
async function splitPdf(){ if(state.files.length!==1) throw new Error("PDF 拆分一次请选择 1 个 PDF。"); const src=await readPdf(state.files[0]); const ranges=(rangeInput.value||`1-${src.getPageCount()}`).split(";").map(x=>x.trim()).filter(Boolean); for(let i=0;i<ranges.length;i++){ const out=await PDFDocument.create(); const pages=await out.copyPages(src,parseRanges(ranges[i],src.getPageCount())); pages.forEach(p=>out.addPage(p)); addResult(`split-${i+1}.pdf`, await out.save({useObjectStreams:true})); } }
async function extractPdf(){ if(state.files.length!==1) throw new Error("页面提取/重排一次请选择 1 个 PDF。"); const src=await readPdf(state.files[0]); const out=await PDFDocument.create(); const pages=await out.copyPages(src,parseRanges(rangeInput.value,src.getPageCount())); pages.forEach(p=>out.addPage(p)); addResult("pages-reordered.pdf", await out.save({useObjectStreams:true})); }
async function deletePagesPdf(){ if(state.files.length!==1) throw new Error("删除页面一次请选择 1 个 PDF。"); const src=await readPdf(state.files[0]); const remove=new Set(parseRanges(rangeInput.value,src.getPageCount())); if(remove.size>=src.getPageCount()) throw new Error("不能删除全部页面。"); const out=await PDFDocument.create(); const pages=await out.copyPages(src,src.getPageIndices().filter(i=>!remove.has(i))); pages.forEach(p=>out.addPage(p)); addResult("pages-deleted.pdf", await out.save({useObjectStreams:true})); }
async function rotatePdf(){ if(state.files.length!==1) throw new Error("旋转页面一次请选择 1 个 PDF。"); const pdf=await readPdf(state.files[0]); const angle=Number(angleInput.value); parseRanges(rangeInput.value||`1-${pdf.getPageCount()}`,pdf.getPageCount()).forEach(i=>{ const p=pdf.getPage(i); p.setRotation(degrees(((p.getRotation().angle||0)+angle)%360)); }); addResult("pages-rotated.pdf", await pdf.save({useObjectStreams:true})); }
async function watermarkPdf(){ if(state.files.length!==1) throw new Error("加水印一次请选择 1 个 PDF。"); const pdf=await readPdf(state.files[0]); const font=await pdf.embedFont(StandardFonts.HelveticaBold); const text=watermarkInput.value||"Confidential"; pdf.getPages().forEach(p=>{ const {width,height}=p.getSize(); p.drawText(text,{x:width*.18,y:height*.48,size:Math.min(width,height)*.08,font,color:rgb(.72,.08,.06),opacity:.22,rotate:degrees(-28)}); }); addResult("watermarked.pdf", await pdf.save({useObjectStreams:true})); }
async function imagesToPdf(){ if(!state.files.length) throw new Error("请至少选择 1 张图片。"); const out=await PDFDocument.create(); for(const f of state.files){ const bytes=await f.arrayBuffer(); const img=f.name.toLowerCase().endsWith(".png") ? await out.embedPng(bytes) : await out.embedJpg(bytes); const maxW=595.28,maxH=841.89,scale=Math.min(maxW/img.width,maxH/img.height,1),w=img.width*scale,h=img.height*scale; const p=out.addPage([maxW,maxH]); p.drawImage(img,{x:(maxW-w)/2,y:(maxH-h)/2,width:w,height:h}); } addResult("images.pdf", await out.save({useObjectStreams:true})); }
async function pdfToImages(){ if(state.files.length!==1) throw new Error("PDF 转图片一次请选择 1 个 PDF。"); const src=await pdfjsLib.getDocument({data:await state.files[0].arrayBuffer()}).promise; const zip=new JSZip(); for(let n=1;n<=src.numPages;n++){ setProgress(Math.round(n/src.numPages*85),`正在渲染第 ${n} / ${src.numPages} 页`); const page=await src.getPage(n); const vp=page.getViewport({scale:2}); const c=document.createElement("canvas"); c.width=Math.ceil(vp.width); c.height=Math.ceil(vp.height); const ctx=c.getContext("2d",{alpha:false}); await page.render({canvasContext:ctx,viewport:vp,background:"white"}).promise; const png=await new Promise(resolve=>c.toBlob(async b=>resolve(await b.arrayBuffer()),"image/png")); zip.file(`page-${String(n).padStart(3,"0")}.png`,png); } addResult("pdf-pages.zip", await zip.generateAsync({type:"uint8array"}), "application/zip"); }
async function compressPdf(){ if(state.files.length!==1) throw new Error("压缩一次请选择 1 个 PDF。"); const pdf=await readPdf(state.files[0]); addResult("optimized.pdf", await pdf.save({useObjectStreams:true,addDefaultPage:false})); }
function resetRedaction(clearRects=true){ const r=state.redaction; r.file=null; r.doc=null; r.pageNumber=1; r.pageCount=0; r.drawing=null; r.renderToken++; if(clearRects) r.rects={}; emptyState.classList.remove("hidden"); canvasShell.classList.add("hidden"); updateRedactLabels(); }
function redactRects(page=state.redaction.pageNumber){ if(!state.redaction.rects[page]) state.redaction.rects[page]=[]; return state.redaction.rects[page]; }
function totalRedactRects(){ return Object.values(state.redaction.rects).reduce((s,l)=>s+l.length,0); }
function updateRedactLabels(){ const r=state.redaction; pageLabel.textContent=r.pageCount?`第 ${r.pageNumber} 页 / 共 ${r.pageCount} 页`:"第 0 页 / 共 0 页"; rectCount.textContent=`已画 ${totalRedactRects()} 个涂黑区域`; }
function overlayPoint(e){ const b=overlayCanvas.getBoundingClientRect(); return {x:(e.clientX-b.left)*(overlayCanvas.width/b.width), y:(e.clientY-b.top)*(overlayCanvas.height/b.height)}; }
function normalizeRect(a,b){ const maxX=overlayCanvas.width/state.redaction.scale,maxY=overlayCanvas.height/state.redaction.scale; const x=Math.max(0,Math.min(a.x,b.x)), y=Math.max(0,Math.min(a.y,b.y)); const right=Math.min(maxX,Math.max(a.x,b.x)), bottom=Math.min(maxY,Math.max(a.y,b.y)); return {x,y,width:right-x,height:bottom-y}; }
function drawPreviewRect(rect,active){ const s=state.redaction.scale; overlayCtx.save(); overlayCtx.fillStyle=active?"rgba(184,50,43,.20)":"rgba(184,50,43,.26)"; overlayCtx.strokeStyle=active?"#b8322b":"#0e6f5c"; overlayCtx.lineWidth=3; overlayCtx.fillRect(rect.x*s,rect.y*s,rect.width*s,rect.height*s); overlayCtx.strokeRect(rect.x*s,rect.y*s,rect.width*s,rect.height*s); overlayCtx.restore(); }
function drawOverlay(){ overlayCtx.clearRect(0,0,overlayCanvas.width,overlayCanvas.height); redactRects().forEach(r=>drawPreviewRect(r,false)); if(state.redaction.drawing) drawPreviewRect(normalizeRect(state.redaction.drawing.start,state.redaction.drawing.current),true); updateRedactLabels(); }
async function prepareRedaction(){ if(tool.value!=="redact") return; if(state.files.length!==1||!state.files[0].name.toLowerCase().endsWith(".pdf")){ resetRedaction(false); return; } const file=state.files[0]; if(state.redaction.file===file&&state.redaction.doc){ await renderRedactPage(); return; } resetRedaction(true); viewerTitle.textContent=file.name; emptyState.classList.add("hidden"); canvasShell.classList.remove("hidden"); state.redaction.file=file; state.redaction.doc=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise; state.redaction.pageCount=state.redaction.doc.numPages; state.redaction.pageNumber=1; await renderRedactPage(); }
async function renderRedactPage(){ const r=state.redaction; if(!r.doc) return; const token=++r.renderToken; const page=await r.doc.getPage(r.pageNumber); const vp=page.getViewport({scale:r.scale}); const w=Math.ceil(vp.width), h=Math.ceil(vp.height); pdfCanvas.width=w; pdfCanvas.height=h; overlayCanvas.width=w; overlayCanvas.height=h; canvasStack.style.width=`${w}px`; canvasStack.style.height=`${h}px`; pdfCtx.fillStyle="#fff"; pdfCtx.fillRect(0,0,w,h); await page.render({canvasContext:pdfCtx,viewport:vp,background:"white"}).promise; if(token!==r.renderToken) return; drawOverlay(); }
async function exportRedactedPdf(){ if(state.files.length!==1) throw new Error("可视化涂黑一次请选择 1 个 PDF。"); if(!totalRedactRects()) throw new Error("请先画出至少 1 个涂黑区域。"); const src=await pdfjsLib.getDocument({data:await state.files[0].arrayBuffer()}).promise; const out=await PDFDocument.create(); for(let n=1;n<=src.numPages;n++){ setProgress(Math.round(n/src.numPages*85),`正在写入第 ${n} / ${src.numPages} 页涂黑区域`); const page=await src.getPage(n); const vp=page.getViewport({scale:2}); const c=document.createElement("canvas"); c.width=Math.ceil(vp.width); c.height=Math.ceil(vp.height); const ctx=c.getContext("2d",{alpha:false}); ctx.fillStyle="#fff"; ctx.fillRect(0,0,c.width,c.height); await page.render({canvasContext:ctx,viewport:vp,background:"white"}).promise; ctx.fillStyle="#000"; (state.redaction.rects[n]||[]).forEach(r=>ctx.fillRect(r.x*2,r.y*2,r.width*2,r.height*2)); const png=await new Promise(resolve=>c.toBlob(async b=>resolve(new Uint8Array(await b.arrayBuffer())),"image/png")); const img=await out.embedPng(png); const p=out.addPage([vp.width/2,vp.height/2]); p.drawImage(img,{x:0,y:0,width:vp.width/2,height:vp.height/2}); } addResult("redacted-visual-raster.pdf", await out.save({useObjectStreams:true})); }
function setRedactMode(mode){ state.redaction.mode=mode; rectTool.classList.toggle("active",mode==="rect"); panTool.classList.toggle("active",mode==="pan"); overlayCanvas.style.pointerEvents=mode==="rect"?"auto":"none"; }
function syncTool(){ const info=toolInfo[tool.value]; activeTool.textContent=info[0]; notice.textContent=info[1]; notice.className=tool.value==="pdf2word"||tool.value==="office2pdf"?"notice bad":tool.value==="compress"?"notice warn":"notice"; fileInput.accept=info[2]; acceptText.textContent=info[3]==="image"?"当前功能需要图片文件。":info[3]==="office"?"当前功能需要 Office 文件。":"当前功能需要 PDF 文件。"; rangeWrap.classList.toggle("hidden",!["split","delete","extract","rotate"].includes(tool.value)); watermarkWrap.classList.toggle("hidden",tool.value!=="watermark"); angleWrap.classList.toggle("hidden",tool.value!=="rotate"); redactStudio.classList.toggle("active",tool.value==="redact"); results.innerHTML=""; progress.classList.remove("active"); if(tool.value==="redact") prepareRedaction().catch(e=>showError(e.message)); }
function showError(message){ results.innerHTML=`<div class="notice bad">${message}</div>`; }
async function run(){ results.innerHTML=""; if(!state.files.length) return showError("请先选择文件。"); try{ setProgress(10,"读取本地文件"); if(tool.value==="merge") await mergePdfs(); else if(tool.value==="split") await splitPdf(); else if(tool.value==="delete") await deletePagesPdf(); else if(tool.value==="extract") await extractPdf(); else if(tool.value==="rotate") await rotatePdf(); else if(tool.value==="watermark") await watermarkPdf(); else if(tool.value==="images") await imagesToPdf(); else if(tool.value==="pdfimages") await pdfToImages(); else if(tool.value==="compress") await compressPdf(); else if(tool.value==="redact") await exportRedactedPdf(); else throw new Error(toolInfo[tool.value][1]); setProgress(100,"处理完成，未上传服务器"); }catch(e){ setProgress(100,"处理停止"); showError(e.message); } }
fileInput.addEventListener("change",e=>{ state.files=Array.from(e.target.files||[]); renderFiles(); resetRedaction(true); syncTool(); });
$(".drop").addEventListener("dragover",e=>{ e.preventDefault(); $(".drop").classList.add("drag"); });
$(".drop").addEventListener("dragleave",()=>$(".drop").classList.remove("drag"));
$(".drop").addEventListener("drop",e=>{ e.preventDefault(); $(".drop").classList.remove("drag"); state.files=Array.from(e.dataTransfer.files||[]); renderFiles(); resetRedaction(true); syncTool(); });
fileList.addEventListener("click",e=>{ const i=e.target.dataset.remove; if(i===undefined) return; state.files.splice(Number(i),1); fileInput.value=""; renderFiles(); resetRedaction(true); syncTool(); });
tool.addEventListener("change",syncTool);
$("#runBtn").addEventListener("click",run);
$("#clearBtn").addEventListener("click",()=>{ state.files=[]; fileInput.value=""; renderFiles(); resetRedaction(true); results.innerHTML=""; progress.classList.remove("active"); });
rectTool.addEventListener("click",()=>setRedactMode("rect"));
panTool.addEventListener("click",()=>setRedactMode("pan"));
zoomInput.addEventListener("change",async()=>{ state.redaction.scale=Number(zoomInput.value); await renderRedactPage(); });
$("#prevPage").addEventListener("click",async()=>{ if(!state.redaction.doc||state.redaction.pageNumber<=1) return; state.redaction.pageNumber--; await renderRedactPage(); });
$("#nextPage").addEventListener("click",async()=>{ if(!state.redaction.doc||state.redaction.pageNumber>=state.redaction.pageCount) return; state.redaction.pageNumber++; await renderRedactPage(); });
$("#undoBtn").addEventListener("click",()=>{ redactRects().pop(); drawOverlay(); });
$("#clearPageBtn").addEventListener("click",()=>{ state.redaction.rects[state.redaction.pageNumber]=[]; drawOverlay(); });
$("#clearAllBtn").addEventListener("click",()=>{ state.redaction.rects={}; drawOverlay(); });
overlayCanvas.addEventListener("pointerdown",e=>{ if(!state.redaction.doc||state.redaction.mode!=="rect") return; e.preventDefault(); overlayCanvas.setPointerCapture(e.pointerId); const p=overlayPoint(e); state.redaction.drawing={start:{x:p.x/state.redaction.scale,y:p.y/state.redaction.scale},current:{x:p.x/state.redaction.scale,y:p.y/state.redaction.scale}}; drawOverlay(); });
overlayCanvas.addEventListener("pointermove",e=>{ if(!state.redaction.drawing) return; e.preventDefault(); const p=overlayPoint(e); state.redaction.drawing.current={x:p.x/state.redaction.scale,y:p.y/state.redaction.scale}; drawOverlay(); });
overlayCanvas.addEventListener("pointerup",e=>{ if(!state.redaction.drawing) return; e.preventDefault(); const p=overlayPoint(e); const rect=normalizeRect(state.redaction.drawing.start,{x:p.x/state.redaction.scale,y:p.y/state.redaction.scale}); state.redaction.drawing=null; if(rect.width>4&&rect.height>4) redactRects().push(rect); drawOverlay(); });
overlayCanvas.addEventListener("pointercancel",()=>{ state.redaction.drawing=null; drawOverlay(); });
setRedactMode("rect");
renderFiles();
syncTool();
